services:   
  #Nginx Service
  nginx:
    container_name: nginx
    image: nginx:alpine    
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80    
    volumes:
      - ./:/var/www      
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      appointhq-network:
  
  #PHP Service
  api:
    build:
      args:
        user: www
        uid: 1000
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: appointhq-dev-app
    image: appointhq-dev-app    
    restart: unless-stopped
    tty: true
    ports:
      - 9000:9000
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      appointhq-network: 

#Docker Networks
networks:
  appointhq-network:
    driver: bridge
